project_name: nada-datastream

builds:
  - env: [ CGO_ENABLED=0 ]
    targets:
      - linux_amd64
      - darwin_amd64
    main: ./
    binary: nada-datastream

release:
  github:
    owner: navikt
    name: nada-datastream

checksum:
  name_template: 'checksums.txt'